on:
push:
branches:
- master
name: "Test it"
job:
build:
name: Test it
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: actions/setup-python@v2
- run: pip install Django
- run: cd django_project
- run: python manage.py runserver
