name: test_Django
on: [push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cypress/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - run: pip install Django
      - run: python ../django_project/manage.py runserver &
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/e2e/spec.cy.js
          browser: chrome
