name: test_Django
on: [push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install Django
      - run: cd django_project/django_project
      - run: ls
      - run: python ./manage.py runserver
